# Generated by Django 3.2.8 on 2021-11-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(default='Django, React', verbose_name='Skills that is required...'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
