# Generated by Django 3.2.8 on 2021-11-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211122_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='min_salary',
        ),
        migrations.AddField(
            model_name='job',
            name='after_meeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='max_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='work_time',
            field=models.PositiveIntegerField(default=1, verbose_name='Work time in hours'),
        ),
    ]
