# Generated by Django 3.2.8 on 2021-11-02 14:06

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='phone_number',
            field=models.BigIntegerField(default=99361000001, validators=[django.core.validators.MinValueValidator(99361000000), django.core.validators.MaxValueValidator(99365999999)], verbose_name='Contact phone number'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='companies/'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='freelancers/'),
        ),
    ]
